Issue 53
devhatt/pet-dex-backend pull request #100
Opened 2024-03-15 23:34 UTC by RenanppCosta

Closes #53 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>
  Rota de listagem de pets para usuários sem autenticação. Limitando informações e quantidade dos pets.

</details>

<details open> 
  <summary>
    <b>Bugfix</b>
  </summary>

- **Description**
N/A

- **Cause**
N/A

- **Solution**
N/A
</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
N/A
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

  - [x] Issue linked
  - [x] Build working correctly
  - [x] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
Kinha me auxilio bastante a entender melhor a arquitetura do projeto e a forma como pensar nele. E Lefel me ajudou a entender melhor o uso dos testes.
</details>

2024-03-18 13:08 UTC, devlefel requested changes
so falta alguns pequenos ajustes para o approve

2024-03-18 13:15 UTC, kvnbg commented on api/routes/routes.go
> +			r.Get("/user-no-auth", controllers.PetController.ListByUserNoAuth)
Na minha visão pode ser um GET pets/ consultando os pets normalmente, indifirente se o usuário está logado ou não. Esse lógica de retorna todos ou 8, por exemplo, poderia colocar no controller ou usecase. 

Exemplo, no controller valida se na requisição foi passado um token JWT válido no header Authorization. Se sim, você retorna a listagem dos pets conforme consultado, se não, retorna a listagem com a limitação de 8 pets (por exemplo).

2024-03-18 13:32 UTC, kvnbg requested changes
Comentei umas melhorias, mas se o pessoal aprovar, por mim tá tranquilo.

2024-03-18 13:32 UTC, kvnbg commented on api/controllers/pet.go
> +		w.WriteHeader(http.StatusNoContent)
Acredito que o status code ideal caso o retorno seja um lista vazia seria o 200. 

O status 204 é idealmente usado para endpoints que, em todas das chamadas, não retornarão conteúdo (DELETE, por exemplo). Como no caso desse endpoint se trata de uma consulta ao recurso de pets e o usuário sempre esperará um body na resposta da API, acredito que o ideal seja retorna um 200 com o array vazio.

A primeira resposta dessa thread tem uma boa explicação [Link](https://stackoverflow.com/questions/13366730/proper-rest-response-for-empty-table)

2024-03-18 13:32 UTC, kvnbg commented on api/controllers/pet.go
> +		w.WriteHeader(http.StatusNoContent)
@devlefel, mas se você aprovar, por mim de boa.

2024-03-24 14:35 UTC, k1nha commented on api/routes/routes.go
> +			r.Get("/user-no-auth", controllers.PetController.ListByUserNoAuth)
concordo cm o kevin

2024-06-12 15:28 UTC, closed without merging