feat: add build & test workflow
devhatt/pet-dex-backend pull request #101
Opened 2024-03-20 17:24 UTC by PiluVitu

Closes 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

N/A
</details>

<details open> 
  <summary>
    <b>Bugfix</b>
  </summary>

- **Description**
N/A

- **Cause**
N/A

- **Solution**
N/A
</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
N/A
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

  - [ ] Issue linked
  - [ ] Build working correctly
  - [ ] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
N/A
</details>

2024-03-21 00:42 UTC, aalmeida00 requested changes

2024-03-21 00:42 UTC, aalmeida00 commented on .github/workflows/main.yml
> +    branches: ["main"]
Só ve se a sintax funciona assim, não precisa tá num array se só tem 1 valor

```suggestion
    branches: 
      - main
```

2024-03-21 00:47 UTC, k1nha commented on .github/workflows/main.yml
> +          go-version: "1.21"
eu acho q tem precisa especificar a versao a fundo, mas n tenho certeza

2024-03-21 00:53 UTC, devlefel submitted a review, later dismissed
- Separar e renomear os arquivos
- Usar dockerfile para etapa de build

2024-03-21 00:53 UTC, devlefel commented on .github/workflows/main.yml
> +        run: go get ./...
`go mod tidy`

2024-03-21 00:54 UTC, devlefel commented on .github/workflows/main.yml
> +          go-version: "1.21"
A versao nao importa tanto aqui NESSE PONTO

2024-03-28 14:13 UTC, aalmeida00 approved these changes

2024-04-01 13:02 UTC, fpmux reviewed
Creio estar tudo certo, só atualizar as versões e mandar bala

2024-04-01 13:02 UTC, fpmux commented on .github/workflows/test.yml
> +      - uses: actions/checkout@v3
v4

2024-04-02 21:52 UTC, PiluVitu commented on go.mod
> -go 1.21.4
A action apontava q essa era a maneira certa de colocar a versão era retirando o numero minor, particularmente não sei como funciona a versão do go, mas o que real importa é a major e patch

2024-04-02 21:52 UTC, PiluVitu commented on .github/workflows/test.yml
> +      - uses: actions/checkout@v3
onde tu vê as versões ?

2024-04-03 02:07 UTC, fpmux approved these changes

2024-04-03 12:03 UTC, k1nha approved these changes
boaa!

2024-04-12 00:21 UTC, merged