feat: automated integration testing process
devhatt/pet-dex-backend pull request #105
Opened 2024-03-27 04:49 UTC by efipemux

Closes 
#103 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Services and a dedicated workflow for integration testing using docker compose.
</details>

<details open> 
  <summary>
    <b>Bugfix</b>
  </summary>

- **Description**
N/A

- **Cause**
N/A

- **Solution**
N/A
</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
N/A
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

  - [x] Issue linked
  - [ ] Build working correctly
  - [ ] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
N/A
</details>

2024-04-01 22:53 UTC, k1nha approved these changes

2024-04-01 22:53 UTC, k1nha commented on .env.example
porque a mudamos a env pra lowercase?

2024-04-01 22:53 UTC, k1nha commented on api/routes/router.go
e se for mudar. temos que validar isso aqui também 
`!= development`

2024-04-06 18:27 UTC, PiluVitu commented
Pr do splash era para estar listado nos commits dessa branch ?

2024-04-16 17:09 UTC, devlefel requested changes

2024-04-16 17:09 UTC, devlefel commented on api/routes/routes.go
> +			r.Get("/{id}", controllers.PetController.FindPet)
modifica para petID para deixar na mesma logica

2024-04-16 17:09 UTC, devlefel commented on infra/db/pet_repository.go
Galera, vamos usar o sqlx  como padrao?
https://github.com/jmoiron/sqlx

Ja usamos em Usuario

2024-05-03 14:00 UTC, PiluVitu commented
Esse é o atual ambiente de desenvolvimento, vou jogar as imagens para alpine, ta batendo um tamanho considerável nas imagens
![image](https://github.com/devhatt/pet-dex-backend/assets/69992923/5f393e04-2476-451e-809d-e22dd96b8b2e)

2024-05-21 22:11 UTC, PiluVitu commented
Preciso: 
- Ajustar workflow de teste unitario  
- Rodar as migrations no build

2024-05-30 14:07 UTC, closed without merging