Consultar ONG #111
devhatt/pet-dex-backend pull request #117
Opened 2024-04-08 19:20 UTC by AtilaRocha

Closes #111 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>
Criado uma rota que recebe um ID de ONG e retorna as informações dessa ONG. Alguns componentes foram criados para pesquisar e interagir com o banco de dados para buscar e retornar essas informações quando necessário. 
<details> 
  <summary>
    <b>Changelog</b>
  </summary>
N/A
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

  - [ ] Issue linked
  - [ ] Build working correctly
  - [ ] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
N/A
</details>

2024-04-08 20:36 UTC, k1nha approved these changes

2024-04-09 19:44 UTC, kvnbg commented
@AtilaRocha, entendo que sua issue ainda está em desenvolvimento, poderia atualizar a PR para "Draft"? Quando finalizar o desenvolvimento você passa ele para "Open" novamente.

2024-04-16 03:17 UTC, kvnbg requested changes
no api/main.go ficou faltando instanciar o OngController para poder ser usado no api/routes.go

2024-04-16 03:17 UTC, kvnbg commented on infra/db/ong_repository.go
> +	panic("unimplemented")
Ficou faltando a implementação da consulta da ONG

2024-04-18 17:32 UTC, k1nha commented on api/main.go
> +	OngController := controllers.NewOngController(OngUseCase)
boa, só manteria o mesmo padrão de camelCase

2024-04-18 17:35 UTC, k1nha requested changes

2024-04-18 17:35 UTC, k1nha commented on api/main.go
> +	OngController := controllers.NewOngController(OngUseCase)
boa, só manteria o padrão de camelCase

2024-04-18 17:35 UTC, k1nha commented on infra/db/ong_repository.go
> +// FindByID implements interfaces.OngRepository.
```suggestion

```
remover esse comentário

2024-04-18 17:35 UTC, k1nha commented on infra/db/ong_repository.go
> +	}
porque só fazemos o scan do id e do name? a consulta de ong não deveria retornar uma ong "completa"?

2024-04-18 18:15 UTC, kvnbg requested changes

2024-04-18 18:15 UTC, kvnbg commented on infra/db/ong_repository.go
> +            ongs
Essa tabela não existe

2024-04-18 18:15 UTC, kvnbg commented on infra/db/ong_repository.go
> +		&ong.Name,
usando o sqlx tem uma forma melhor de atribuir valores que retornam do banco

```go
var data;
err = db.Select(&data, "SELECT * FROM table where id = ?", 1) 
```

Dessa forma, o que retorna do SELECT ele vai associar a entity, desde que os nomes da propriedade e das colunas da tabela sejam os mesmos

2024-05-03 14:33 UTC, PiluVitu commented
@AtilaRocha sua branch foi criado de maneira certa pae ? 
Parece q tu herdou alguns commits que não deveriam estar aqui

![image](https://github.com/devhatt/pet-dex-backend/assets/69992923/1af2eaab-b14f-446f-a4e3-e0f899ad70bb)

2024-06-12 15:26 UTC, closed without merging