Desenvolver endpoint de atualizar usuário #31
devhatt/pet-dex-backend pull request #124
Opened 2024-04-16 02:08 UTC by kvnbg

Closes #31 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Desenvolvido o endpoint para atualizar campos do usuário de acordo com a tela de configuração do usuário do protótipo.
</details>

<details open> 
  <summary>
    <b>Bugfix</b>
  </summary>

- **Description**
N/A

- **Cause**
N/A

- **Solution**
N/A
</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
N/A
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

  - [X] Issue linked
  - [X] Build working correctly
  - [X] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
N/A
</details>

2024-04-16 02:41 UTC, k1nha commented on infra/db/user_repository.go
> +
é a melhor forma de se fazer isso?

2024-04-16 02:41 UTC, k1nha approved these changes

2024-04-16 02:51 UTC, kvnbg commented on infra/db/user_repository.go
> +
pior que acho que sim, não achei outra forma que fuja dessa lógica

2024-04-16 16:51 UTC, devlefel requested changes

2024-04-16 16:51 UTC, devlefel commented on api/controllers/user.go
>  	uusecase *usecase.UserUsecase
pode retirar o u amais

2024-04-16 16:51 UTC, devlefel commented on cmd/main.go
Pq retirou tudo de main do cmd?

2024-04-16 16:51 UTC, devlefel commented on infra/db/user_repository.go
> +
é a que normalmente uso, mas tem uma forma com o banco senao me engano mas vale a pesquisa

2024-04-16 16:51 UTC, devlefel commented on infra/db/user_repository.go
> +
mas nao seria interessante usar namedExec para deixar a query mais legivel? tirando os ? e colocando os :nomeDaPropriedade

2024-04-16 17:32 UTC, kvnbg commented on api/controllers/user.go
>  	uusecase *usecase.UserUsecase
Onde tem u a mais? Não consegui localizar onde tá marcado

2024-04-22 00:37 UTC, devlefel commented on cmd/main.go
é utilizado para testar a app sem subir toda a API =D

2024-04-26 21:05 UTC, devlefel approved these changes

2024-04-26 21:41 UTC, merged