feat: adicionando birthdate e adoption_date ao UPDATE do pet   -  issue56
devhatt/pet-dex-backend pull request #125
Opened 2024-04-18 21:37 UTC by yuri-silveiraa

Closes 

<details open> 
  <summary>
    <b>adicionando birthdate e adoption_date ao UPDATE do pet</b>
  </summary>

N/A
</details>

<details open> 
  <summary>
    <b>Bugfix</b>
  </summary>

- **Description**
N/A

- **Cause**
N/A

- **Solution**
N/A
</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
N/A
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

  - [ ] Issue linked
  - [ ] Build working correctly
  - [x] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
N/A
</details>

2024-04-18 23:03 UTC, kvnbg requested changes
Fazer o rebase com a main para resolver os conflitos, teve um merge recente na main

2024-04-18 23:03 UTC, kvnbg commented on usecase/pet.go
> +	fmt.Println(petToUpdate.Size + "")
remover esse "log"

2024-04-18 23:03 UTC, kvnbg commented on usecase/pet.go
> +		return fmt.Errorf("failed to update for pet with ID %s: %w", petID, err)
Quando fizer o rebase com main, adiciona também a linha de log informando o erro

2024-04-18 23:39 UTC, devlefel requested changes

2024-04-18 23:39 UTC, devlefel commented on usecase/pet.go
> +    if size != "" {
Pode retirar essa parte a @mmaysc ja ajustou

2024-04-25 23:11 UTC, devlefel approved these changes

2024-04-25 23:12 UTC, devlefel approved these changes

2024-04-26 10:25 UTC, kvnbg approved these changes

2024-04-26 10:27 UTC, merged