Issue#112
devhatt/pet-dex-backend pull request #130
Opened 2024-05-04 21:36 UTC by Clerijr

Closes 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>
Adiciona endpoint de update de Ong
</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
N/A
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

  - [ ] Issue linked
  - [x] Build working correctly
  - [ ] Tests created
</details>

<details open> 
  <summary>
    <b>Additional info</b>
  </summary>
Utiliza dos serviços de FindById de Ong e de Update de User
</details>

2024-05-08 17:57 UTC, zoldyzdk requested changes

2024-05-08 17:57 UTC, zoldyzdk commented on infra/db/ong_repository.go
> +	values := []interface{}{}
Man o Go tem uma preferência na forma de declarar slices vazios, dá uma olhada:
https://go.dev/wiki/CodeReviewComments#declaring-empty-slices

2024-05-08 17:57 UTC, zoldyzdk commented on usecase/ong.go
> +	if err != nil {
esse err deveria receber algo na linha anterior não? pra então testar se teve erro?

2024-05-09 19:31 UTC, k1nha approved these changes
bom pr, só resolver a questão do logger

2024-05-09 19:31 UTC, k1nha commented on api/controllers/ong.go
esse logger está sendo usado de outro controller (breed)
deveria usar da seguinte forma: `oc.logger`

2024-05-10 10:52 UTC, zoldyzdk approved these changes

2024-05-13 17:16 UTC, k1nha approved these changes

2024-05-13 17:17 UTC, merged