Issue 128 - Rota de Pegar uma unica breed
devhatt/pet-dex-backend pull request #133
Opened 2024-05-10 20:27 UTC by luanc202

Closes #128 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Adiciona endpoint GET de Breed por ID, utilizando a função criada de FindByID do usecase de Breed.
</details>

<details open> 
  <summary>
    <b>Bugfix</b>
  </summary>

- **Description**
N/A

- **Cause**
N/A

- **Solution**
N/A
</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
N/A
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

  - [x] Issue linked
  - [x] Build working correctly
  - [x] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
N/A
</details>

2024-05-14 02:26 UTC, zoldyzdk requested changes

2024-05-14 02:26 UTC, zoldyzdk commented on api/controllers/breed.go
> +func (cntrl *BreedController) FindBreed(w http.ResponseWriter, r *http.Request) {
O Go tem uma recomendação pra que os receivers dos métodos tenham um nome só

2024-05-14 13:26 UTC, luanc202 commented on api/controllers/breed.go
> +func (cntrl *BreedController) FindBreed(w http.ResponseWriter, r *http.Request) {
renomeado

2024-05-14 21:52 UTC, zoldyzdk approved these changes

2024-05-20 13:47 UTC, zoldyzdk approved these changes

2024-05-21 16:17 UTC, devlefel approved these changes

2024-05-21 16:22 UTC, merged