Issue 111
devhatt/pet-dex-backend pull request #134
Opened 2024-05-16 00:27 UTC by Clerijr

Closes #111 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Criado endpoint para receber um Ong ID e retornar uma entidade Ong
</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

  - [x] Issue linked
  - [ ] Build working correctly
  - [ ] Tests created
</details>

<details open> 
  <summary>
    <b>Additional info</b>
  </summary>
O usecase reaproveita o repositorio de User para trazer os componentes de user da Ong
</details>

2024-05-16 14:01 UTC, k1nha commented on api/controllers/ong.go
> +		logger.Error("error on ong controller: ", err)
logger na linha 52

e utilizar o oc.logger na 59

2024-05-16 14:03 UTC, k1nha requested changes

2024-05-16 14:03 UTC, k1nha commented on infra/db/ong_repository.go
deixamos de usar o database/sql e estamos no sqlx pela praticidade 

https://github.com/jmoiron/sqlx

2024-05-16 15:08 UTC, k1nha commented on api/controllers/ong.go
> +		logger.Error("error on ong controller: ", err)
ficou o logger aqui
```suggestion
		oc.logger.Error("error on ong controller: ", err)
```

2024-05-16 15:16 UTC, k1nha commented on infra/db/ong_repository.go
> +
mudou para sqlx mas não implementou o sqlx

```go
  jason = Person{}
  err = db.Get(&jason, "SELECT * FROM person WHERE first_name=$1", "Jason")
```

2024-05-16 15:16 UTC, k1nha requested changes
.

2024-05-21 16:08 UTC, devlefel approved these changes

2024-05-21 21:35 UTC, merged