Listagem de ONGs
devhatt/pet-dex-backend pull request #138
Opened 2024-05-20 18:06 UTC by DominMFD

Closes #110 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Foi implementado um endpoint GET que faz a Listagem de ONGs no banco de dados. Também foi implementado a paginação e a ordenação em ordem crescente e decrescente de nome e endereço.
</details>

<details open> 
  <summary>
    <b>Bugfix</b>
  </summary>

  - [x] Issue linked
  - [x] Build working correctly
  - [ ] Tests created
</details>

2024-05-20 19:07 UTC, k1nha commented on api/controllers/ong.go
> +		w.WriteHeader(http.StatusInternalServerError)
vamos usar o logger que está no proprio controller `oc.logger`

2024-05-20 19:09 UTC, k1nha requested changes

2024-05-20 19:09 UTC, k1nha commented on api/controllers/ong.go
> +		logger.Error("error listing ongs", err)
vamos usar o logger que está no proprio controller `oc.logger`

2024-05-20 19:09 UTC, k1nha commented on entity/dto/ong_list_dto.go
> +
remover essa linha em branco

2024-05-20 19:09 UTC, k1nha commented on infra/db/ong_repository.go
estamos usando sqlx, seria bom usar a implementação recomedada por eles
vou deixar a referência: https://github.com/jmoiron/sqlx?tab=readme-ov-file#usage

2024-05-20 19:09 UTC, k1nha commented on usecase/ong.go
só implementar o logger e utilizar caso ocorra erro

2024-05-20 19:28 UTC, DominMFD commented on infra/db/ong_repository.go
muito obrigado kinha

2024-05-22 22:42 UTC, devlefel requested changes

2024-05-22 22:42 UTC, devlefel commented on entity/dto/ong_list_dto.go
> +type OngList struct {
OngList nao devia ser um slide de ong? aka Ong[]

2024-05-24 20:37 UTC, devlefel approved these changes

2024-06-03 14:45 UTC, devlefel approved these changes

2024-06-03 17:12 UTC, k1nha approved these changes

2024-06-03 17:12 UTC, merged