Atualização da ultilização dos logs
devhatt/pet-dex-backend pull request #145
Opened 2024-06-06 17:14 UTC by oswaldo-oliveira

Closes 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

N/A
</details>

<details open> 
  <summary>
    <b>Bugfix</b>
  </summary>

- **Description**
Usecase com ultilização de logs de forma incorreta.

- **Cause**
N/A

- **Solution**
Utilização dos logs nos seguintes useacases (breed, pet e ong)
</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
N/A
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

![image](https://github.com/devhatt/pet-dex-backend/assets/98189208/42257f1b-19e5-4190-b839-2486b68c97ae)

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

  - [x] Issue linked
  - [x] Build working correctly
  - [ ] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
N/A
</details>

2024-06-10 11:02 UTC, zoldyzdk requested changes

2024-06-10 11:02 UTC, zoldyzdk commented on usecase/pet.go
> +		c.logger.Error("error updating pet", err)
Faltou os dois pontos espaço no final da mensagem de erro

2024-06-10 11:02 UTC, zoldyzdk commented on usecase/breed.go
>  		err = fmt.Errorf("error listing breeds: %w", err)
Acho que não precisamos mais desse fmt de error

2024-06-10 13:28 UTC, devlefel approved these changes

2024-06-12 16:07 UTC, zoldyzdk approved these changes

2024-06-12 16:36 UTC, merged