Issue 37 - Fazer Layer de repositório e package de email
devhatt/pet-dex-backend pull request #146
Opened 2024-06-06 22:01 UTC by muritadb

Closes #37 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Criado interface para o envio e notificação de emails repositorios.
</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

  - [x] Issue linked
  - [ ] Build working correctly
  - [ ] Tests created
</details>

2024-06-10 10:52 UTC, zoldyzdk requested changes
Murita algo muito errado aconteceu ai, não tem como tu ter mexido em 86 arquivos kkkk

2024-06-20 21:57 UTC, zoldyzdk approved these changes

2024-06-20 21:59 UTC, muritadb commented
@Felipeness i need some review in my task, plis

2024-06-23 01:49 UTC, GabrielTrindadeC requested changes
Acredito que esta faltando algumas coisas, a task compreende a implementação do package, testes e use cases.

2024-06-24 15:03 UTC, devlefel requested changes
@muritadb aonde esta a implementacao dessa interface? 

Precisamos dela nessa feature aqui

2024-07-16 21:17 UTC, zoldyzdk requested changes

2024-07-16 21:17 UTC, zoldyzdk commented on infra/mail_repository.go
> +	message := mail.NewMessage(to, "olaaaa este é um email de confirmação!!!")
Acho que é melhor botar uma msg mais padrão, esse olaaaa ta meio estranho kkk

2024-07-16 21:33 UTC, muritadb commented on infra/mail_repository.go
> +	message := mail.NewMessage(to, "olaaaa este é um email de confirmação!!!")
kkksda era teste

2024-07-23 20:56 UTC, zoldyzdk approved these changes

2024-07-23 20:57 UTC, merged