Issue 36
devhatt/pet-dex-backend pull request #150
Opened 2024-06-13 21:32 UTC by thiagoCalazans-dev

Closes #36 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Feat entire application Push Notification endpoint flow
</details>

<details open> 
  <summary>
    <b>Bugfix</b>
  </summary>

- **Description**
N/A

- **Cause**
N/A

- **Solution**
N/A
</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
N/A
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

  - [x] Issue linked
  - [x] Build working correctly
  - [x] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
N/A
</details>

2024-06-14 21:19 UTC, thiagoCalazans-dev commented
/assign @thiagoCalazans-dev

2024-06-18 11:59 UTC, zoldyzdk requested changes
Acredito que tem uns commits que não faz parte do seu PR

2024-06-19 20:59 UTC, GabrielTrindadeC approved these changes

2024-06-23 02:57 UTC, zoldyzdk approved these changes

2024-06-24 15:01 UTC, devlefel approved these changes

2024-06-24 15:02 UTC, merged