feat: Reset User Password
devhatt/pet-dex-backend pull request #151
Opened 2024-06-17 21:16 UTC by patrickn2

Closes #32
WIP

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

N/A
</details>

<details open> 
  <summary>
    <b>Bugfix</b>
  </summary>

- **Description**
N/A

- **Cause**
N/A

- **Solution**
N/A
</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
N/A
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

  - [ ] Issue linked
  - [ ] Build working correctly
  - [ ] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
N/A
</details>

2024-06-19 02:21 UTC, patrickn2 commented
@Felipeness

2024-06-19 20:37 UTC, GabrielTrindadeC approved these changes

2024-06-20 19:04 UTC, zoldyzdk requested changes
Man só um detalhe que acho legal alterar, e ai tem um outro ponto mas que é meio algo estético mesmo que é a inicialização de slices vazios, na funcionalidade não muda nada mas da uma olhada aqui nesse link https://go.dev/wiki/CodeReviewComments#declaring-empty-slices tipo não tem um martelo batido sobre uma das duas que a gente adotaria e tals. Mas é isso muito bom seu código cara!

2024-06-20 20:23 UTC, patrickn2 commented on usecase/user_test.go
> +	hasher := mockInterfaces.NewMockHasher(t)
Done

2024-06-20 20:24 UTC, patrickn2 commented
> Man só um detalhe que acho legal alterar, e ai tem um outro ponto mas que é meio algo estético mesmo que é a inicialização de slices vazios, na funcionalidade não muda nada mas da uma olhada aqui nesse link https://go.dev/wiki/CodeReviewComments#declaring-empty-slices tipo não tem um martelo batido sobre uma das duas que a gente adotaria e tals. Mas é isso muito bom seu código cara!

Sabe me informar onde que eu declarei esses empty slices? Que aí ja corrijo

2024-06-20 21:08 UTC, zoldyzdk approved these changes

2024-06-20 21:35 UTC, merged