Adicionado Golint como workflow
devhatt/pet-dex-backend pull request #157
Opened 2024-07-10 03:01 UTC by luanc202

Closes #155 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Adiciona o [Golangci-lint](https://github.com/marketplace/actions/golangci-lint) os workflows do projeto para poder ser configurado nos checks.
</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

  - [x] Issue linked
  - [x] Build working correctly
  -  <s>Tests created</s>
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
N/A
</details>

2024-07-10 14:51 UTC, PiluVitu requested changes

2024-07-10 14:51 UTC, PiluVitu commented on .github/workflows/golangci-lint.yml
> +      - "master"
Retirar esse master pois a branch principal no repositório é main

2024-07-10 14:51 UTC, PiluVitu commented on .github/workflows/golangci-lint.yml
> +on:
Adicionar no on `workflow_dispatch:` para conseguirmos disparar esse workflow manualmente

2024-07-10 14:51 UTC, PiluVitu commented on .github/workflows/golangci-lint.yml
> +  detect-modules:
para que serve esse detect modules ?

2024-07-10 14:52 UTC, PiluVitu commented
Resolver os erros do workflows

2024-07-15 20:40 UTC, luanc202 commented on .github/workflows/golangci-lint.yml
> +  detect-modules:
faz o setup pra pegar os módulos de Go existentes no diretório, transformar num json e passar pro golangci-lint no `strategy: matrix: modules: ...`
Coloquei ele porquê em um dos exemplos ele estava implementando essa config de strategy, mas ela não é obrigatória e não achei mais info nas docs

2024-07-18 18:59 UTC, PiluVitu requested changes

2024-07-18 18:59 UTC, PiluVitu commented on .github/workflows/golangci-lint.yml
> +  pull_request:
Sugiro que adicione a seguinte alteração no codigo para somente executar o workflow caso o pr esteja direcionado para a main, pois sem essa especificação todo pr aberto poderá rodar esse workflow

```suggestion
  pull_request:
     branches: 
       - "main"
```

2024-07-18 19:33 UTC, luanc202 commented on .github/workflows/golangci-lint.yml
> +  pull_request:
Feito

2024-07-18 20:15 UTC, PiluVitu approved these changes

2024-07-18 20:41 UTC, zoldyzdk approved these changes

2024-07-18 20:41 UTC, merged