Issue 119 - Estudar e implementar swagger na aplicação
devhatt/pet-dex-backend pull request #160
Opened 2024-07-19 21:31 UTC by EdiltonOliveira

Closes 
#119 

<details open> 
  <summary>
    <b> Feature </b>
  </summary>

- Implementação do swag para documentação da API PetDex e um modelo piloto
 - Configuração do comando make swag no arquivo Makefile 
</details>

<details open> 
  <summary>
    <b>Bugfix</b>
  </summary>

- **Description**
N/A

- **Cause**
N/A

- **Solution**
N/A
</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
N/A
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>
![petdex_image](https://github.com/user-attachments/assets/72452f7e-adf3-43a2-8022-90eb6841c3f5)

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

  - [x] Issue linked
  - [ ] Build working correctly
  - [ ] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
N/A
</details>

2024-07-23 20:51 UTC, zoldyzdk requested changes

2024-07-23 20:51 UTC, zoldyzdk commented on api/controllers/user.go
> +// @Router /users/{id} [get]
É bom dar uma melhorada na documentação dessa rota, porque ela meio que vai servir de exemplo pra galera documentar as outras, ai acredito que teríamos algo semelhante a isso aqui:

https://petstore.swagger.io/#/pet/getPetById

Percebe que é basicamente a mesma da que tais implementando, ai tem o parâmetro pra pessoa colocar, e também tem o exemplo do retorno, o json.

![image](https://github.com/user-attachments/assets/9db92519-7738-4267-ab78-630329ea0d34)

![image](https://github.com/user-attachments/assets/b8a01d49-7ce0-4585-add0-e1e45e25f1ef)

2024-07-24 23:31 UTC, EdiltonOliveira commented on api/controllers/user.go
> +// @Router /users/{id} [get]
Opa, Zold! Acredito que consegui contemplar as solicitações. Além disso, adicionei mais coisas para ajudar ao pessoa.

![Captura de tela de 2024-07-24 20-27-23](https://github.com/user-attachments/assets/ec4cca22-ae22-4a15-ae8b-eaed7bab1867)

2024-07-30 20:31 UTC, zoldyzdk requested changes

2024-07-30 20:31 UTC, zoldyzdk commented on api/controllers/pet.go
Vi que você trocou a rota pra documentar né, olha eu tentei fazer um post com o swagger e não consegui por dois motivos principais:
1- Essa rota em específico precisa estar autenticado pra realizar o post, e isso é algo que precisamos ver como é implementado no swagger, provavelmente tem documentação pra fazer isso então já que tais documentando uma assim é interessante também implementar isso como exemplo pras próximas.
2- Mesmo removendo a questão de auth quando fui fazer o post deu body inválido, acredito que tenha algum detalhe ali do model que esteja incorreto, talvez algum campo seja um enum específico de strings ai se não for a string daquele enum vai dar erro.

2024-08-05 18:19 UTC, EdiltonOliveira commented on api/controllers/pet.go
1) Este tópico já foi deliberado e será uma implementação posterior a criação da rota de autenticação

* a nova rota de acesso ao swagger agora é pública.

2) Consegui realizar um cadastro de pet via Postman com a inserção de um body válido.

Json válido para cadastro de Pet.

`{
    "name": "Thor",
    "breed_id": "0e0b8399-1bf1-4ed5-a2f4-b5789ddf5df0",
    "adoption_date": "2008-01-02T15:04:05Z",
    "birthdate": "2006-01-02T15:04:05Z",
    "weight": 4.1,
    "size": "medium"
}`

Imagem para visualização da inserção via swagger (status 201 como retorno) e do banco de dados.

swagger:


![created_pet_swagger](https://github.com/user-attachments/assets/4e052f76-0afb-4592-b1c3-f40f4d0796a9)

Pet cadastrado através do Postman (lado esquerdo) e exibição do cadastro no DB via extensão VScode (Lado direito)

![Captura de tela de 2024-08-05 15-17-53](https://github.com/user-attachments/assets/2e4806c1-6562-4300-ba8a-8004a68f1fdd)

2024-08-09 17:45 UTC, devlefel requested changes

2024-08-09 17:45 UTC, devlefel commented on docs/api/swagger_documentation.md
muda o caminho dessa doc e coloca ela como um topico do contribution guide na raiz?

2024-08-10 00:31 UTC, EdiltonOliveira commented on docs/api/swagger_documentation.md
Todas as solicitações foram atendidas. Agora aguardando revisão.

2024-08-10 00:33 UTC, EdiltonOliveira commented on docs/api/swagger_documentation.md
![Captura de tela de 2024-08-09 21-09-29](https://github.com/user-attachments/assets/1e8fa832-19a7-4c21-b717-44be4b506e90)

Identifiquei um bug que estava impedindo de compilar o projeto, então fiz a alteração e isso gerou um conflito que não consigo corrigir localmente. É apenas para correção da rota de delete, pois faltou / no caminho.

2024-08-14 18:28 UTC, devlefel approved these changes

2024-08-14 18:29 UTC, devlefel approved these changes

2024-08-14 18:44 UTC, merged