Documentação do PATCH da ONG
devhatt/pet-dex-backend pull request #194
Opened 2024-09-05 12:26 UTC by DominMFD

Closes #183

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Foi criado a documentação através do swagger de UPDATE da Ong

</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>

Para a conclusão dessa task foi necessário mudar o tipo do Link no `OngUpdateDto` pois o swagger não identifica o tipo json.RawMessage e por isso não documenta o mesmo, para resolver esse problema foi criado uma Struct de Link só para o update e na função `OngToUpdate` tem a conversão do Link para json.RawMessage

</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

![image](https://github.com/user-attachments/assets/6174c323-3a3a-461b-b6db-76116fd32466)

![image](https://github.com/user-attachments/assets/4316f1d0-5449-4df8-b105-c81847915e0b)

![image](https://github.com/user-attachments/assets/c276f876-69a5-429b-b405-b8b44fdc725a)

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

  - [x] Issue linked
  - [x] Build working correctly
  - [ ] Tests created
</details>

2024-09-05 21:04 UTC, davidambz commented on entity/dto/ong_update_dto.go
> +}
Esse struct do Link, não seria melhor deixar em outro arquivo? pq acredito que ele vai ser usado em outros lugares, tipo na entity `ong.go`

2024-09-05 22:58 UTC, DominMFD commented on entity/dto/ong_update_dto.go
> +}
Pode ser, bom que a gente já padroniza

2024-09-06 21:52 UTC, juliaam requested changes
está quebrado 
![image](https://github.com/user-attachments/assets/85e233ee-bf48-4a4f-a379-39d2c1d39581)

2024-09-09 19:55 UTC, juliaam requested changes

2024-09-09 19:55 UTC, juliaam commented on api/controllers/ong.go
> +// @Description Retrieves Ong details based on the ong ID provided as a parameter.
parece que ele vai apenas retornar e não fazer um update
```suggestion
// @Description Updates the details of an existing Ong based on the provided Ong ID.
```

2024-09-09 19:55 UTC, juliaam commented on api/controllers/ong.go
> +// @Param ongID path string true "Ong id to be retrieved"
```suggestion
// @Param ongID path string true "Ong id to be updated"
```

2024-09-09 19:55 UTC, juliaam commented on api/controllers/ong.go
> +// @Param ongDto body dto.OngUpdateDto true "Update information of the ong"
```suggestion
// @Param ongDto body dto.OngUpdateDto true "Data to update the Ong"
```

2024-09-09 19:55 UTC, juliaam commented on entity/ong.go
>  	return &Ong{
não falta o id da ong?

2024-09-09 19:59 UTC, juliaam commented on entity/ong.go
>  	return &Ong{
nesse body de retorno?

2024-09-09 21:20 UTC, EdiltonOliveira commented
Testando feature nova CI/CD

2024-09-10 03:03 UTC, Luiginicoletti commented on api/controllers/ong.go
> +// @Description Retrieves Ong details based on the ong ID provided as a parameter.
mas ta escrito duas vezes que vai update rs rs.

<img width="253" alt="Screenshot 2024-09-10 at 00 02 56" src="https://github.com/user-attachments/assets/a35a98cd-1777-4d01-80c8-21426a7ea79c">

2024-09-10 03:08 UTC, Luiginicoletti approved these changes
Bom trabalho Sundeizera! 

![Uploading cao-brabo-gif.gif…]()

2024-09-10 03:08 UTC, Luiginicoletti commented on entity/ong.go
> +	Links          *json.RawMessage					 `json:"links"`
Desculpa a ignorancia o que significa esses espacos?

<img width="796" alt="Screenshot 2024-09-10 at 00 06 36" src="https://github.com/user-attachments/assets/fccd6180-63cf-4023-8cec-add666c93749">

2024-09-10 03:50 UTC, juliaam commented on api/controllers/ong.go
> +// @Description Retrieves Ong details based on the ong ID provided as a parameter.
um é o comentário sobre a documentação, e o outro é a própria doc

2024-09-10 11:01 UTC, DominMFD commented on entity/ong.go
>  	return &Ong{
acho que não, pq não pode atualizar o ID né

2024-09-10 11:02 UTC, DominMFD commented on entity/ong.go
>  	return &Ong{
se bem que ele retorna a ong e não o dto

2024-09-10 21:58 UTC, merged