feat: documentation update user
devhatt/pet-dex-backend pull request #200
Opened 2024-09-11 23:01 UTC by joaomarcelo09

Closes #171 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Documentação da rota de atualização de usuário.
</details>

<details open> 
  <summary>
    <b>Bugfix</b>
  </summary>

- **Description**
N/A

- **Cause**
N/A

- **Solution**
N/A
</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
N/A
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

  - [ ] Issue linked
  - [ ] Build working correctly
  - [ ] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
N/A
</details>

2024-09-12 01:33 UTC, EdiltonOliveira commented on api/controllers/user.go
> +// @Router /users/{userId} [put]
Olá, João Marcelo! Obrigado pelas sua contribuições. Sempre bom receber novos colaboradores. Sobre sua task, notei que não estou conseguindo inserir os dados para atualizar. Você conseguiu inserir ID e Body diretamente pela página da documentação ao clicar na opção "try it out"?

2024-09-12 01:38 UTC, EdiltonOliveira commented on api/controllers/user.go
>  	IDStr := chi.URLParam(r, "id")
Note que tanto a rota r.Patch("/{id}", contro...) está usando id, então você precisa usar o mesmo parâmetro na notação do swagger (// @Param id path string true "User ID"). Sugiro alterar todos para userID (para padronizar ao invés de id ou userId). Acredito que por isso não está funcional a sua rota. Ela deveria parecer com isso aqui 

![Captura de tela de 2024-09-11 22-27-28](https://github.com/user-attachments/assets/72791658-9113-45c2-95bb-52fec9767c25)

Note que ao clicar em try in out foi liberado locais para adicionar ID e um body para atualizar.
OBS: sempre que alterar as anotações swag, gere uma nova doc com o comando make swag.

2024-09-12 01:40 UTC, EdiltonOliveira commented on api/controllers/user.go
> +// @Router /users/{userId} [put]
Altere put para patch, tendo em vista que esse é o método usado pela rota (r.patch("/{id}", contro...)).

Put é um método usado para atualizar todos os campus enquanto que patch dá flexibilidade de alterar apenas alguns (O que provalmente é a proposta).

2024-09-12 14:12 UTC, Luiginicoletti approved these changes

2024-09-19 23:33 UTC, davidambz requested changes
fora isso altera no arquivo de rotas `api/routes/routes.go` na linha 47 o parâmetro pra `userID`
```go
r.Patch("/{userID}", controllers.UserController.Update)
```

2024-09-19 23:33 UTC, davidambz commented on api/controllers/user.go
>  	IDStr := chi.URLParam(r, "id")
```suggestion
	IDStr := chi.URLParam(r, "userID")
```

2024-09-19 23:33 UTC, davidambz commented on api/controllers/user.go
> +// @Router /users/{userId} [put]
aqui é `/user` o método á `patch` e altera o parametro pra `userID`

```suggestion
// @Router /user/{userID} [path]
```

2024-09-20 09:45 UTC, EdiltonOliveira commented on api/controllers/user.go
> +// @Router /users/{userId} [patch]
Alterar userId para userID conforme as rotas e parâmetros definidos.

2024-09-20 13:00 UTC, davidambz commented on api/controllers/user.go
> +// @Router /users/{userId} [put]
userID

2024-09-20 13:51 UTC, davidambz approved these changes

2024-09-20 16:07 UTC, EdiltonOliveira commented
@joaomarcelo09 , você atualizou a doc swagger com o comando make swag após as atualizações? Rodei sua branch aqui e ela exibiu o seguinte erro

![Captura de tela de 2024-09-20 13-05-16](https://github.com/user-attachments/assets/00466469-67db-4a69-8281-5d48561b1172)

Ao atualizar a documentação, a rota funcionou direitinho.

2024-09-20 17:18 UTC, joaomarcelo09 commented
> alizar a documentação, a rota funcionou direitinho.

esqueci de fazer o make swag

2024-09-20 17:49 UTC, juliaam submitted a review, later dismissed
![image](https://github.com/user-attachments/assets/ba8812e2-a776-4e6d-8f59-d270852c082a)
nao esta funcionando!

2024-09-20 17:49 UTC, juliaam commented on api/controllers/user.go
> +// @Failure 404
nao vi nenhum notfound, pode tirar

2024-09-20 17:49 UTC, juliaam commented on swagger/docs.go
isso daqui provavelmente nao está sendo gerado do make swag? tem que ser gerado dele

2024-09-20 21:11 UTC, EdiltonOliveira approved these changes
Task concluída com sucesso! Alterações realizadas, execução normalizada da doc. Parabéns!

2024-09-23 13:24 UTC, davidambz requested changes

2024-09-23 13:24 UTC, davidambz commented on swagger/swagger.json
> +                    "404": {
ainda ta no json, faltou o `make swag`

2024-09-23 19:08 UTC, davidambz approved these changes

2024-09-23 22:41 UTC, merged