ci: adiciona dockerfile
devhatt/pet-dex-backend pull request #64
Opened 2024-01-06 03:00 UTC by lucasvsouza28

Closes #25

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Adiciona dockerfile com build multi-stage
</details>

<details open> 
  <summary>
    <b>Bugfix</b>
  </summary>

- **Description**
N/A

- **Cause**
N/A

- **Solution**
N/A
</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
N/A
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

  - [ ] Issue linked
  - [ ] Build working correctly
  - [ ] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
N/A
</details>

2024-01-06 16:15 UTC, aalmeida00 reviewed
Eu prefiro um código sem comentários, fica mais limpo.

Vale ver com o @Lefel95 o que ele acha.

2024-01-06 16:15 UTC, aalmeida00 commented on Dockerfile
> +CMD ["./pet-dex-api"]
eof

2024-01-09 22:02 UTC, aalmeida00 commented
Alguma atualização aqui?

@lucasvsouza28

2024-01-10 15:00 UTC, lucasvsouza28 commented
> Alguma atualização aqui?
> 
> @lucasvsouza28

Comentários removidos

2024-01-11 03:03 UTC, aalmeida00 approved these changes

2024-01-12 11:58 UTC, Lefel95 requested changes

2024-01-12 11:58 UTC, Lefel95 commented on Dockerfile
> +COPY /api ./
Copia a api antes de dar go mod

2024-01-12 11:58 UTC, Lefel95 commented on Dockerfile
> +EXPOSE 8080
se vai fazer multistage building nao tem pq dar EXPOSE ne? =P

2024-01-12 11:58 UTC, Lefel95 commented on Dockerfile
> +EXPOSE 8080
Verifica com a galera qual e a porta que estao adotando e ve se eh 8080 msm

2024-01-12 11:58 UTC, Lefel95 commented on Dockerfile
> +CMD ["./pet-dex-api"]
Eu prefiro comentarios para partes mais complexas, nao para Run

2024-01-12 17:49 UTC, lucasvsouza28 commented on Dockerfile
> +EXPOSE 8080
Eu copiei da doc oficial do docker porque não vi nenhum PR envolvendo criação dos handlers ainda. Tem alguma preferência?

2024-01-13 13:34 UTC, closed without merging