feat: create mail pkg
devhatt/pet-dex-backend pull request #65
Opened 2024-01-06 21:43 UTC by k1nha

Closes #35 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

N/A
</details>

<details open> 
  <summary>
    <b>Bugfix</b>
  </summary>

- **Description**
N/A

- **Cause**
N/A

- **Solution**
N/A
</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
N/A
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

  - [x] Issue linked
  - [x] Build working correctly
  - [ ] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
  Acho que nesse primeiro momento não precisaríamos usar algum provedor externo, vi alguns pacotes que trabalhavam com email (go-mail, aws ses) e eles tem implementações parecidas, alterando algumas coisas de como é estruturado o email
</details>

2024-01-12 11:55 UTC, Lefel95 requested changes

2024-01-12 11:55 UTC, Lefel95 commented on pkg/mail/config.go
> +		provider = "smtp.gmail.com"
se nao tem provider fi, PANIC

2024-01-12 11:55 UTC, Lefel95 commented on pkg/mail/config.go
> +		provider = "smtp.gmail.com"
Provider nao deveria vir do .env?

2024-01-12 11:55 UTC, Lefel95 commented on pkg/mail/email_request.go
> +	Subject string
E se eu quiser enviar anexo?

2024-01-12 11:55 UTC, Lefel95 commented on pkg/mail/config.go
> +package mail
Toda essa parte de config deveria estar ou em outro package, provavelmente em infra, ou pelo menos aqui mas privada, do jeito que esta, eu posso dar um bypass no seu pacote de email sender e usar sua config :)

2024-01-12 11:55 UTC, Lefel95 commented on pkg/mail/config.go
> +	validEmail := ValidateEmail(emailAddress)
Por que o CreateConfig Valida o email? isso nao ta sobrecarregando a responsabilidade dele?

2024-01-12 11:55 UTC, Lefel95 commented on pkg/mail/mail_test.go
> +	cfg, err := CreateConfig("example@gmail.com", "secret", "")
Falta outros cases, cade o case de erro?

2024-01-12 11:55 UTC, Lefel95 commented on pkg/mail/mail_test.go
> +	cfg, err := CreateConfig("example@gmail.com", "secret", "")
https://dev.to/boncheff/table-driven-unit-tests-in-go-407b

2024-01-15 13:07 UTC, k1nha commented on pkg/mail/config.go
> +package mail
tu pode até tentar mas o pacote interno do smtp provavelmente vai quebrar sua aplicação

a implementação tá bem parecida com de outros pacotes, não consegui pensar numa forma de privar esse config

2024-01-31 21:50 UTC, Lefel95 approved these changes

2024-01-31 21:50 UTC, Lefel95 commented on pkg/mail/mail.go
> +func NewMail(config *Config) *Mail {
Retorna uma interface de mailer

2024-01-31 22:13 UTC, merged