Issue-56: Adiciona propriedades 'Aniversário' e 'Dia de Doação' ao endpoint
devhatt/pet-dex-backend pull request #66
Opened 2024-01-08 17:23 UTC by AtilaRocha

Endpoint de atualização de Pets.

Closes 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

N/A
</details>

<details open> 
  <summary>
    <b>Bugfix</b>
  </summary>

- **Description**
N/A

- **Cause**
N/A

- **Solution**
N/A
</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
N/A
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

  - [ ] Issue linked
  - [ ] Build working correctly
  - [ ] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
N/A
</details>

- Adiciona propriedades 'Aniversário' e 'Dia de Doação' ao endpoint de atualização de Pets.
- Objetivo: Melhorar a experiência do usuário ao permitir a manutenção de registros detalhados sobre eventos importantes na vida do animal.

2024-01-09 15:13 UTC, hxsggsz commented
falta preencher as informações do pull request, logo ao lado do `Closes` coloca #numero-da-sua-issue pra a sua issue ser fechada assim que o pr for mergeada

e eu vi que 80% do seu código ta em portugues, padroniza tudo pra inglês, as mensagends de print e e os comentarios tambem
<img width="347" alt="image" src="https://github.com/devhatt/pet-dex-backend/assets/103784814/74c9d8a2-616f-4c94-af05-f4e6a04581bf">

2024-01-12 11:59 UTC, Lefel95 requested changes

2024-01-12 11:59 UTC, Lefel95 commented on api/controllers/controller.go
> +	Pets = make(map[string]entity.Pet)
Aqui, voce esta usando um map, para substituir a conexao do banco correto?
Uma boa ideia, mas esperarei vc mergear a main na sua branch para trazer o banco para ca.
Alem disso voce poderia ter implementado a interface do repositorio em uma estrutura que retornava esse map, ai no final vc so precisaria mudar a camada do repository :) pode ir modificando essa parte

2024-01-12 11:59 UTC, Lefel95 commented on api/controllers/controller.go
> +		http.Error(w, "Erro ao decodificar a solicitação", http.StatusBadRequest)
Aqui voce pode dar um wrap no erro, para o usuario nao ficar perdido aonde errou

2024-01-12 11:59 UTC, Lefel95 commented on api/controllers/controller.go
> +	if aniversario, ok := requestBody["aniversario"]; ok {
Toda essa logica deveria estar em uma camada de UseCase, que ja temos, nao em um controller, o controller so controla o fluxo de chamadas de comunicacao (nesse caso HTTP) da aplicação.

2024-01-12 11:59 UTC, Lefel95 commented on api/controllers/controller.go
> +func AtualizarDiadeAdocao(w http.ResponseWriter, r *http.Request) {
Essas duas funcoes deveriam ser uma funcao de atualizar so, com um if, vamos seguir o DRY (Dont Repeat Yourself) voce esta repetindo 80% do codigo aqui, para mudar uma propriedade so, e o usuario da API nao tem que ficar batendo em 1 endpoint para cada propriedade :)

2024-01-12 11:59 UTC, Lefel95 commented on api/main.go
> +	go func() {
Não quero que voce retire, nem modifique isso, em vez disso quero que voce me explique esse trecho de codigo, para que ele serve, por que ele existe, e o que esta fazendo aqui. :)

2024-02-26 22:49 UTC, closed without merging