Listar pets do usuário #39
devhatt/pet-dex-backend pull request #67
Opened 2024-01-09 17:58 UTC by davidspader

Closes 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Listar pets do usuário
</details>

<details open> 
  <summary>
    <b>Bugfix</b>
  </summary>

- **Description**
N/A

- **Cause**
N/A

- **Solution**
N/A
</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
N/A
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

  - [ ] Issue linked
  - [ ] Build working correctly
  - [ ] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
Fiz baseado na call que tivemos ontem
</details>

2024-01-09 22:04 UTC, aalmeida00 commented
@davidspader Ótimo PR, mas ele está apontando pra branch errada, pode apontar para a main?
![image](https://github.com/devhatt/pet-dex-backend/assets/61947632/fcd2cf40-147c-4d25-97f3-5223841e2e8b)

2024-01-10 01:24 UTC, davidspader commented
troquei a branch, adicionei o Closes #39 ali tbm, se eu não me engano alguém tinha falado pra eu me colocar como Assignees na daily, mas não consigo fazer isso

2024-01-12 11:37 UTC, Lefel95 requested changes

2024-01-12 11:37 UTC, Lefel95 commented on api/controllers/controller.go
> +func ListUserPets(w http.ResponseWriter, r *http.Request) {
Não está usando usando o muxer do chi feito pelo @k1nha, mergear com a main e ajustar

2024-01-12 11:37 UTC, Lefel95 commented on api/main.go
> +	routes.RoutesHandler()
Está faltando inicializar o Repository, Conexão com DB, UseCase e injeta-los, se mergear com a main vai ter já

2024-01-12 11:37 UTC, Lefel95 commented on cmd/main.go
> +	dbc, err := sql.Open("mysql", "dellis:@/shud")
Lembrando que o cmd/main.go é usado para subirmos testes rapidos localmente via CLI,  entao o que estiver aqui de inicializacao e injecao de dependencia, tem que estar em api/main.go, por que lá é a real entrada do programa

2024-01-12 11:37 UTC, Lefel95 commented on infra/db/pet_repository.go
> +	fmt.Println(rows)
Tem alguma duvida para ler as linhas?

2024-01-12 11:37 UTC, Lefel95 commented on usecase/pet.go
> +		fmt.Printf("failed")
melhora o print do erro, lembre-se do `%w`

2024-01-16 03:29 UTC, Lefel95 requested changes

2024-01-16 03:29 UTC, Lefel95 commented on api/controllers/pet/listUserPets.go
> +package petcontroller
cara nao precisamos de um arquivo para cada controller

2024-01-16 12:31 UTC, davidspader commented on api/controllers/pet/listUserPets.go
> +package petcontroller
Coloco o método dentro do controller **find.go** então?

2024-01-24 01:22 UTC, davidspader commented
@Lefel95 @k1nha 

O que eu ainda preciso fazer?

2024-02-24 00:12 UTC, Lefel95 requested changes
Cara tirando o package de email que ali deu ruim, recomendo chamar @k1nha 
Tenho poucas mudancas citadas.

Mas vou falar algo aqui nao vou deixar passar, falta testes!
Como ja tive call de testes, e tem ate pacote de exemplo, da uma revisada e qualquer pergunta manda ai.

2024-02-24 00:12 UTC, Lefel95 commented on api/controllers/pet/find.go
>  func (cntrl *FindPetController) FindPet(w http.ResponseWriter, r *http.Request) {
Mudar para FindByUserID

2024-02-24 00:12 UTC, Lefel95 commented on pkg/mail/config.go
Pq esse cara é novo? Não é do @k1nha ?

2024-02-24 00:12 UTC, Lefel95 commented on pkg/mail/mail.go
Mesma coisa do acima @k1nha

2024-02-24 00:12 UTC, Lefel95 commented on pkg/mail/mail_test.go
Mesma coisa do acima @k1nha

2024-02-24 00:12 UTC, Lefel95 commented on pkg/mail/message.go
mesma coisa do acima @k1nha

2024-02-24 00:12 UTC, Lefel95 commented on pkg/mail/validate.go
Aqui tbm @k1nha

2024-02-24 00:42 UTC, davidspader commented on api/controllers/pet/find.go
esse controller já estava no código, mexi nele só pro código voltar a rodar com as alterações que eu fiz.

2024-02-24 00:43 UTC, davidspader commented on api/controllers/pet/find.go
>  func (cntrl *FindPetController) FindPet(w http.ResponseWriter, r *http.Request) {
esse FindPet é pra buscar o pet pelo próprio ID, eu também mexi nele só pro código voltar a rodar com as alterações que eu fiz.

2024-02-24 00:44 UTC, davidspader commented on pkg/mail/config.go
Sim, foi o @k1nha que fez, não sei pq ta aqui

2024-02-24 00:44 UTC, davidspader commented on pkg/mail/mail_test.go
Sim, foi o @k1nha que fez, não sei pq ta aqui

2024-02-24 00:45 UTC, davidspader commented on pkg/mail/validate.go
Acho que deu algum problema com o rebase

2024-03-02 19:25 UTC, k1nha commented on usecase/pet.go
> +func (c *PetUseCase) FindById(id uuid.UUID) (*entity.Pet, error) {
Nesse caso, devemos usar nossa implementação de uuid, elá está dentro da pasta `pkg/entity/id`

seria algo assim: 
```go
func (c *PetUseCase) FindById(id uniqueEntity.ID) (*entity.Pet, error) {
```
lembra de importar o pacote assim
```go
import(
	...
	uniqueEntity "pet-dex-backend/v2/pkg/entity"
)

```

2024-03-02 19:26 UTC, k1nha commented on usecase/pet.go
No caso do uso da biblioteca do `google/uuid` devemos usar nossa implementação de uuid, elá está dentro da pasta `pkg/entity/id`

seria algo assim: 
```go
func (c *PetUseCase) FindById(id uniqueEntity.ID) (*entity.Pet, error) {
```
lembra de importar o pacote assim
```go
import(
	...
	uniqueEntity "pet-dex-backend/v2/pkg/entity"
)

```

2024-03-02 19:27 UTC, k1nha commented on interfaces/pet_repository.go
Devemos usar a mesma implementação do nosso pkg aqui

2024-03-02 19:29 UTC, k1nha commented on infra/db/pet_repository.go
> +		if pet.AdoptionDate, err = time.Parse("2006-01-02", adoptionDateStr); err != nil {
talvez seja valido colocar o "2006-01-02" em uma variavel p reutilizar, já que usamos elas em alguns lugares

2024-03-02 19:30 UTC, k1nha commented on infra/db/pet_repository.go
> +func (pr *PetRepository) ListPetsByUserID(userID uuid.UUID) (pets []*entity.Pet, err error) {
Já que estamos no repository de pet, não faria mais sentido se o nome da função fosse: `ListByUser`

e também devemos usar nossa implementação de uuid, elá está dentro da pasta pkg/entity/id

2024-03-02 19:30 UTC, k1nha commented on infra/db/pet_repository.go
> +func (pr *PetRepository) FindById(id uuid.UUID) (pet *entity.Pet, err error) {
aqui também devemos usar nossa implementação de uuid, elá está dentro da pasta pkg/entity/id

2024-03-02 19:36 UTC, k1nha commented on api/routes/routes.go
Aqui acho valido a gente discutir qual seria o melhor endpoint pra colocar
@Lefel95 

Deixar como `pets/my-pets/{user_id}` ou `user/{id}/my-pets`

2024-03-02 19:37 UTC, k1nha commented on api/controllers/pet.go
> +	userID, err := uuid.Parse(idStr)
devemos usar nossa implementação de uuid para parse

acho que o nome ListPetsByUser seria mais claro

2024-03-02 19:40 UTC, k1nha commented on usecase/pet_test.go
boaaa! só mudar o uuid pro nosso package e tá top

talvez ser um pouco mais descritivo no nomes das funções

2024-03-02 19:43 UTC, k1nha requested changes
Bom PR, só algumas mudanças em nomes de variáveis/funções e utilizar nosso pkg de uuid

fique livre para discutir as mudanças

2024-03-04 00:35 UTC, Lefel95 requested changes
Mudanças de UUID e de nomenclatura todas listadas nos comentarios

2024-03-04 00:35 UTC, Lefel95 commented on api/routes/routes.go
Concordo!

2024-03-04 00:35 UTC, Lefel95 commented on entity/pet.go
> +	ImageUrl            string    `json:"image_url,omitempty"`
Retirar o omitempty

2024-03-04 00:35 UTC, Lefel95 commented on infra/db/pet_repository.go
> +	"github.com/google/uuid"
Usa o nosso pkg de uuid

2024-03-04 00:35 UTC, Lefel95 commented on usecase/pet_test.go
> +func TestListUserPetsInvalidUserID(t *testing.T) {
Renomear para TestListUserPetsErrorOnRepo

2024-03-05 00:30 UTC, k1nha approved these changes

2024-03-05 22:09 UTC, devlefel approved these changes

2024-03-05 22:28 UTC, merged