Fazer Conexao de Banco de dados e Muxer Chi
devhatt/pet-dex-backend pull request #69
Opened 2024-01-09 21:26 UTC by k1nha

Closes #68 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

N/A
</details>

<details open> 
  <summary>
    <b>Bugfix</b>
  </summary>

- **Description**
N/A

- **Cause**
N/A

- **Solution**
N/A
</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
N/A
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

  - [ ] Issue linked
  - [ ] Build working correctly
  - [ ] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
N/A
</details>

2024-01-10 21:56 UTC, Lefel95 requested changes

2024-01-10 21:56 UTC, Lefel95 commented on api/controllers/pet/create.go
> +	usecase := NewPetUseCase(db.NewPetRepository())
Nao podemos inicializar banco, Repositorio e Services a cada chamada HTTP, imaginemos que estaremos recebendo 5000 Requests, estaremos abrindo 5000 connection pools com o banco, adicionaramos, 5000 instancias de usecase e repository na memoria?

2024-01-10 21:56 UTC, Lefel95 commented on api/main.go
> +	config.InitConfigs()
Devemos inicializar os usecases e repositories aqui uma unica vez, e injeta-los na camada de controller/routing

2024-01-11 01:10 UTC, Lefel95 requested changes

2024-01-11 01:10 UTC, Lefel95 commented on api/main.go
> +	router.Use(middleware.AllowContentType("application/json"))
Isso deveria estar na camada de Roteamento nao no main

2024-01-11 01:10 UTC, Lefel95 commented on api/controllers/pet/example.go
> +	db := config.GetDB()
O example controller ta pegando db e executando direto da camada?
como a gente ta trabalhando com pessoas mais juniores seria interessante deixar mais palpavel a realidade nao?
Adiciona uma rotina HelloWorld na Usecase e no repository, e com isso fazemos um exemplo em todas as camadas com Hello World :)

2024-01-11 02:54 UTC, k1nha commented on api/controllers/pet/example.go
> +	db := config.GetDB()
boaa, tinha esquecido

2024-01-11 19:13 UTC, Lefel95 requested changes

2024-01-11 21:07 UTC, Lefel95 approved these changes

2024-01-11 21:17 UTC, PiluVitu approved these changes
Vai q é tua

2024-01-11 21:17 UTC, GabrielTrindadeC approved these changes

2024-01-11 21:17 UTC, aalmeida00 approved these changes

2024-01-11 21:17 UTC, aalmeida00 commented on .env.example
> +PORT=3000
eof

2024-01-11 21:18 UTC, merged