Cadastro de ONG
devhatt/pet-dex-backend pull request #72
Opened 2024-01-12 14:31 UTC by luanc202

Closes #40 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Recebe um POST para cadastro de ONGs na rota `/api/ong/`
</details>

<details open> 
  <summary>
    <b>Bugfix</b>
  </summary>

- **Description**
N/A

- **Cause**
N/A

- **Solution**
N/A
</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
N/A
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

  - [ ] Issue linked
  - [ ] Build working correctly
  - [ ] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
Li os comentários nas PRs recentes e levei em consideração nos últimos dois commits
</details>

2024-01-13 15:21 UTC, k1nha approved these changes

2024-01-16 03:39 UTC, Lefel95 requested changes

2024-01-16 03:39 UTC, Lefel95 commented on api/controllers/ong/create.go
> +package ongcontroller
nao precisamos criar uma pasta de ong, criamos um arquivo ong.go dentro de controller que vai ter tudo do DOMINIO de ong

2024-01-16 03:39 UTC, Lefel95 commented on usecase/create_ong.go
> +package usecase
renomeie o arquivo para ong.go ela vai caber muito mais do que o create

2024-01-19 00:27 UTC, luanc202 commented on api/controllers/ong/create.go
> +package ongcontroller
Lógica movida para ong.go ✅

2024-01-19 00:27 UTC, luanc202 commented on usecase/create_ong.go
> +package usecase
Renomeado para ong.go ✅

2024-01-23 23:12 UTC, Lefel95 requested changes

2024-01-23 23:12 UTC, Lefel95 commented on api/controllers/ong.go
> +func NewCreateOngcontroller(usecase *usecase.OngUseCase) *CreateOngController {
NewOngController

2024-01-23 23:12 UTC, Lefel95 commented on api/controllers/ong.go
> +type CreateOngController struct {
OngController

2024-01-23 23:12 UTC, Lefel95 commented on api/controllers/ong.go
> +	if err != nil {
loga o erro, pelo menos

2024-01-23 23:12 UTC, Lefel95 commented on api/controllers/ong.go
> +		w.WriteHeader(400)
aqui é 500 e nos dois  status use o pacote http.Status

2024-01-23 23:12 UTC, Lefel95 commented on entity/ong.go
> +type Ong struct {
Está Faltando o campo userID

2024-01-23 23:12 UTC, Lefel95 commented on infra/db/ong_repository.go
> +	rows, err := or.dbconnection.Query("INSERT INTO ongs (cnpj, email, address, city, state, image, facebook, instagram) VALUES (?,?,?,?,?,?,?,?)", ong.CNPJ, ong.Email, ong.Location.Address, ong.Locatio
Faltou o campo UserID

2024-01-23 23:12 UTC, Lefel95 commented on usecase/ong.go
> +	err := c.repo.Save(ong)
Aqui seria interessante verificarmos se existe um usuario com aquele uuid passado, pq senao vai existir CNPJ sem Usuario

2024-01-25 02:57 UTC, luanc202 commented on usecase/ong.go
> +	err := c.repo.Save(ong)
Eu até pensei em fazer aí mesmo a query para verificar se existe o usuário, mas aí eu estaria roubando a responsabilidade do que poderia ser uma função `findUserById` no usecase de users.

Posso fazer a query aí mesmo, ou fazemos uma nova issue para o CRUD de usuários e incluir o usecase lá para depois chamar aqui, ou fazer o mínimo da entity de User para poder chamar o `findUserById`?

2024-01-25 02:57 UTC, luanc202 commented on infra/db/ong_repository.go
> +	rows, err := or.dbconnection.Query("INSERT INTO ongs (cnpj, email, address, city, state, image, facebook, instagram) VALUES (?,?,?,?,?,?,?,?)", ong.CNPJ, ong.Email, ong.Location.Address, ong.Locatio
Adicionado ✅

2024-01-25 02:58 UTC, luanc202 commented on entity/ong.go
> +type Ong struct {
Adicionado no commit mais recente ✅

2024-01-25 02:58 UTC, luanc202 commented on api/controllers/ong.go
> +		w.WriteHeader(400)
Adicionado no commit mais recente ✅

2024-01-25 02:58 UTC, luanc202 commented on api/controllers/ong.go
> +	if err != nil {
Adicionado no commit mais recente ✅

2024-02-26 22:52 UTC, closed without merging