Fazer Endpoint de Atualizar Pet
devhatt/pet-dex-backend pull request #73
Opened 2024-01-12 19:36 UTC by iasarchi

Closes #43

<details open> 
  <summary>
    <b>Feature</b>
  </summary>
Criacao de endpoint para atualizacao do porte de pet.

N/A
</details>

<details open> 
  <summary>
    <b>Bugfix</b>
  </summary>

- **Description**
N/A

- **Cause**
N/A

- **Solution**
N/A
</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
N/A
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

  - [x] Issue linked
  - [x] Build working correctly
  - [ ] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
N/A
</details>

2024-01-14 22:34 UTC, k1nha commented on api/controllers/pet/update.go
> +	}
```suggestion
	paramId := chi.URLParam(r, "id")
	convetedId, err := strconv.Atoi(id)
	if err != nil {
		fmt.Errorf("Invalid id!")
		w.WriteHeader(400)
		return
	}
```

2024-01-14 22:35 UTC, k1nha commented on api/controllers/pet/update.go
> +	err := cntrl.UseCase.Do(convetedId, petToBeUpdated.PetDetails.Size)
```suggestion
	err := cntrl.UseCase.Do(paramId, petToBeUpdated.PetDetails.Size)
```

2024-01-14 22:36 UTC, k1nha commented on api/controllers/pet/update.go
> +		w.Write([]byte("Invalid Id"))
faltou o return e por enquanto vamos mandar somente o status code
```suggestion
		w.WriteHeader(400)
		return
```

2024-01-14 22:39 UTC, k1nha commented on api/controllers/pet/update.go
é bom deixar o nome mais declarativo, tanto do arquivo quanto das variáveis/funções, temos alguns outros updates no app e talvez confunda o pessoal

2024-01-14 22:39 UTC, k1nha commented on api/main.go
> +		UpdateSizeController: updateController,
alterar como sugerido

2024-01-14 22:40 UTC, k1nha requested changes
só algumas alterações

2024-01-15 13:52 UTC, iasarchi commented on api/controllers/pet/update.go
> +	err := cntrl.UseCase.Do(convetedId, petToBeUpdated.PetDetails.Size)
pq o paramId vem como string

2024-01-15 13:52 UTC, iasarchi commented on api/controllers/pet/update.go
> +	err := cntrl.UseCase.Do(convetedId, petToBeUpdated.PetDetails.Size)
coloquei como convertId pq o paramId vem como string e no caso preciso receber um inteiro.

2024-01-15 13:59 UTC, iasarchi commented on api/controllers/pet/update.go
> +	}
Nesse caso e porque ja tinha uma variavel com o nome (err) declarada mais abaixo

2024-01-16 03:45 UTC, Lefel95 requested changes

2024-01-16 03:45 UTC, Lefel95 commented on api/controllers/pet/update.go
Aqui na verdade entra como pet.go ou pet.controller.go por que aqui vai caber muito mais de pet do que atualizar

2024-01-16 03:45 UTC, Lefel95 commented on api/controllers/pet/update.go
> +func NewUpdatePetController(usecase *usecase.UpdateUseCase) *UpdatePetController {
Modificar para PetController

2024-01-16 03:45 UTC, Lefel95 commented on api/controllers/pet/update.go
> +	err := cntrl.UseCase.Do(convetedId, petToBeUpdated.PetDetails.Size)
@iasarchi muda para Update somente, e receba o parametro de size dentro dele, do jeito que esta vamos ter que ter um endpoint para cada propriedade, nao queremos isso =X

2024-01-16 03:45 UTC, Lefel95 commented on api/routes/routes.go
> +			r.Patch("/{id}/size", controllers.UpdateSizeController.UpdateSize)
Patch /{id}/ @iasarchi

2024-02-02 12:05 UTC, closed without merging