Configuração de migrations para versionamento das alteraçoes no banco…
devhatt/pet-dex-backend pull request #77
Opened 2024-01-22 20:49 UTC by kvnbg

Closes  #76 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Configuração de migrations para versionamento das alteraçoes no banco…
</details>

<details open> 
  <summary>
    <b>Bugfix</b>
  </summary>

- **Description**
N/A

- **Cause**
N/A

- **Solution**
N/A
</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
N/A
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

  - [ ] Issue linked
  - [ ] Build working correctly
  - [ ] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
N/A
</details>

2024-01-22 21:08 UTC, Lefel95 requested changes

2024-01-22 21:08 UTC, Lefel95 commented on infra/config/migration.go
> +		"file://"+env.MIGRATIONS_PATH,
tem jeitos melhores de carregar arquivos, e ainda por cima, o que precisa ser passado aqui? o caminho? relativo ou total? ou a instancia do arquivo? pq em nenhuma dessas 3 o file:// como protocolo faz sentido para mim

2024-01-22 21:08 UTC, Lefel95 commented on migrations/20240117151749_init_db.up.sql
> +    avatar     varchar(255),
vamos trocar o avatar para avatarUrl para deixar mais explicito

2024-01-22 21:08 UTC, Lefel95 commented on migrations/20240117151749_init_db.up.sql
> +    link           json,
esse link poderia ser links nao? tem varios ali

2024-01-22 21:08 UTC, Lefel95 commented on migrations/20240117151749_init_db.up.sql
> +CREATE TABLE IF NOT EXISTS pets
Vai dar errado vc criar um pets com dependencia em breed sendo que nao criou o breed

2024-01-22 21:08 UTC, Lefel95 commented on migrations/20240117151749_init_db.up.sql
> +    physicalCharact varchar(255),
physicalCharacteristics eh o correto, podemos mudar para physicalChar

2024-01-22 21:10 UTC, Lefel95 commented on infra/config/migration.go
> +		"file://"+env.MIGRATIONS_PATH,
https://pkg.go.dev/os

https://gobyexample.com/reading-files

2024-01-23 18:38 UTC, Lefel95 approved these changes

2024-01-23 20:52 UTC, k1nha approved these changes

2024-01-23 20:53 UTC, merged