Fazer Endpoint de Atualizar Pet #43
devhatt/pet-dex-backend pull request #87
Opened 2024-02-09 13:30 UTC by iasarchi

Closes #43 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>
Criado endpoint de atualizar pet
Modificada a entidade pets
</details>

<details open> 
  <summary>
    <b>Bugfix</b>
  </summary>

- **Description**
N/A

- **Cause**
N/A

- **Solution**
N/A
</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
N/A
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

  - [x] Issue linked
  - [x] Build working correctly
  - [x] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
N/A
</details>

2024-02-09 21:33 UTC, k1nha commented on usecase/pet.go
acredito que o usecase de update deveria estar aqui dentro

2024-02-09 21:38 UTC, k1nha commented on usecase/update.go
> +	//}
É valido ter esse código para prevenir alguma invariancia futuramente

2024-02-09 21:39 UTC, k1nha commented on usecase/update_test.go
> +
Porque está comentado?

2024-02-09 21:39 UTC, k1nha commented on usecase/update_test.go
> +//	}
Porque está comentado?

2024-02-09 21:42 UTC, k1nha reviewed
-

2024-02-09 22:57 UTC, kvnbg commented on usecase/update_test.go
> +
porque dependia do findbyid que nao estava funcionando, ai estou aguardando correcao

2024-02-09 22:58 UTC, iasarchi commented on usecase/pet.go
Tinha entendi que o usecase ficaria separado desta forma e so no controller que ficaria agrupado em um arquivo só

2024-02-09 23:02 UTC, iasarchi commented on usecase/update_test.go
> +
Mesmo do comentário de cima.  Código está comentado, ai não tem como executar o teste da forma correta, pois precisa do FindById descomentado.

2024-02-09 23:02 UTC, iasarchi commented on usecase/update.go
> +	//}
Sim. Está comentado porque o FindById não está de acordo com as atualizações do banco de dados. Ia falar com o pessoal hoje sobre isso

2024-02-09 23:03 UTC, iasarchi commented on usecase/update_test.go
> +//	}
Mesmo do comentário de cima.  Código está comentado, ai não tem como executar o teste da forma correta, pois precisa do FindById descomentado.

2024-02-09 23:03 UTC, iasarchi commented on usecase/update_test.go
> +//	}
Esse eu comentei sem querer. Vou ajustar

2024-02-21 01:38 UTC, Felipeness commented on api/controllers/pet.go
Tratamento de Erros
 Tenta usar uma biblioteca de logging ou algo que te dê mais controle sobre como os erros são mostrados.
Quando você retorna um erro para o usuário, usar as constantes como http.StatusBadRequest ao invés de apenas colocar o número do erro (400, por exemplo) pode deixar o código mais legível.

Fechando o Body da Requisição
É uma boa ideia fechar o body da requisição depois de usá-lo. Isso ajuda a liberar recursos mais rapidamente. Você pode fazer isso adicionando defer r.Body.Close() logo após começar a tratar a requisição.

Resposta JSON
Antes de enviar a resposta, seria legal definir o tipo de conteúdo como JSON, assim: w.Header().Set("Content-Type", "application/json"). Isso garante que quem recebe a resposta saiba que é um JSON, mas pode ficar muito limitado, faz um teste só para ver como fica

2024-02-21 01:38 UTC, Felipeness commented on api/errors/erro.go
Usar o prefixo Err para nomes de erros. Você já fez isso com ErrInvalidID, o que está ótimo. Para manter a consistência, você poderia renomear InvalidBody para ErrInvalidBody.

Uso de Interfaces
 Se todos os seus erros customizados implementarem a interface error do Go (o que requer apenas um método Error() string), você pode manipulá-los mais facilmente em outras partes do código, fazemos isso muito em Java, pode fazer aqui também
 
 
 Pensei em algo assim :
 
 
 package errors

type ErrInvalidID struct {
	Description string `json:"description"`
}


type ErrInvalidBody struct {
	Description string `json:"description"`
}


func (e *ErrInvalidID) Error() string {
	return e.Description
}

func (e *ErrInvalidBody) Error() string {
	return e.Description
}

2024-02-22 01:12 UTC, Lefel95 requested changes
Tem algumas mudanças que preciso que você faça.

Outros comentários servem somente para entender melhor a lógica.

Enquanto outros são para melhorias futuras e não precisa travar o PR.

Boa Sorte! 🤠

2024-02-22 01:12 UTC, Lefel95 commented on usecase/update.go
> +package usecase
Usecase/ update?
Update o que?
Update tudo?

@iasarchi acho melhor ser um usecase de pet e dentro dele ter uma função de update não? Aí eu pego a lógica de negócio de pet e atualizo o pet.

`petUsecase.Update()`

2024-02-22 01:12 UTC, Lefel95 commented on usecase/update.go
> +	//}
> É valido ter esse código para prevenir alguma invariancia futuramente

Parabéns pelo uso da palavra invariancia

2024-02-22 01:12 UTC, Lefel95 commented on usecase/update.go
> +	if &petToUpdate.Size != nil && petToUpdate.Size != "" && c.IsValidSize(petToUpdate.Size) {
Pode tirar essa segunda validação ela tem que estar no `isValidSize()`
Para um size ser válido ele não pode ser vazio

2024-02-22 01:12 UTC, Lefel95 commented on usecase/update.go
> +	updateValues := map[string]interface{}{}
Essa aqui eh uma melhoria para um futuro vamos abrir uma issue, não bloqueia a PR ok?

O ideal eh que o model seja passado para o repo e ele que seja usado para atualização, nem que seja um DTO ou um modelo de atualização, falo isso pq criar outra variável Cria fricção de interface entre repo e usecase e gasta mais memória.

Para isso vamos implementar uma biblioteca de SQL para nós ajudar.

Mas como um improve e não para parar essa PR ok @iasarchi ?

2024-02-22 01:12 UTC, Lefel95 commented on usecase/update_test.go
> +package usecase
@iasarchi Parabéns pelos testes!
Eles estão limpos, claros e seguindo uma boa estrutura!

Nos próximos testes eu gostaria que você viesse com uma margem para melhoria:

- testes de mesa: https://dave.cheney.net/2019/05/07/prefer-table-driven-tests

- padrão AAA: https://brain.d.foundation/Engineering/Backend/Testing+Made+Simple+Best+Practices+for+Golang+Test#:~:text=The%20AAA%20pattern%20provides%20a,variables%20required%20for%20the%20test.

Será que vem uma próxima talk sua @iasarchi ? 👀

2024-03-03 13:39 UTC, iasarchi commented on api/controllers/pet.go
> +	repository interfaces.PetRepository
Eu confundi ai, nao foi intencional

2024-03-03 14:38 UTC, Felipeness approved these changes
NICE PR, boas soluções e implementação, continue assim

2024-03-03 20:22 UTC, k1nha commented on api/routes/routes.go
> +			r.Patch("/{petID}", controllers.PetController.Update)
as rotas tao duplicadas, só apagar a de cima

2024-03-03 20:27 UTC, iasarchi commented on api/routes/routes.go
> +			r.Patch("/{petID}", controllers.PetController.Update)
As rotas estão como foi definido quando o Kevin apresentou pro Lefel. 

Tem a /users que é referente ao usuário
E a de pet que é /users/{userid}/pets

2024-03-04 01:27 UTC, Lefel95 approved these changes
@iasarchi Ta aprovado, so por favor deleta o legacy code comentado antes do merge pf?

2024-03-04 01:27 UTC, Lefel95 commented on api/routes/routes.go
> +			r.Patch("/{petID}", controllers.PetController.Update)
@iasarchi acho que o que o @k1nha quis dizer era que /users deveria ser um grupo entao ficaria assim:
```r.Route("/users", func(r chi.Router) {
            r.Route("/{userID}/pets", func(r chi.Router) {
			            r.Patch("/{petID}", controllers.PetController.Update)
		})
		```
		
Nao deveria ser assim? Mas nao é block nao

2024-03-04 01:27 UTC, Lefel95 commented on usecase/pet.go
Retirar comentarios do codigo legado, pode deletar

2024-03-04 01:27 UTC, Lefel95 commented on usecase/pet_test.go
> +//func TestUpdateUseCaseDoPetNotFound(t *testing.T) {
Pode deletar

2024-03-04 21:53 UTC, merged