Cadastro de pet
devhatt/pet-dex-backend pull request #91
Opened 2024-03-07 02:19 UTC by luanc202

Closes #42 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Cria a rota para cadastrar pet com Nome, Id da raça e Id do usuário

</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

Nenhum.
</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

  - [x] Issue linked
  - [x] Build working correctly
  - [x] Tests created
</details>

<details open> 
  <summary>
    <b>Additional info</b>
  </summary>
N/A
</details>

2024-03-08 11:07 UTC, Felipeness commented on api/controllers/pet/create.go
Quando você retorna um erro após cntrl.UseCase.Save(pet) falhar, é uma boa prática enviar alguma mensagem ao cliente, assim como fez no erro de decodificação JSON. Além disso, usar http.StatusBadRequest diretamente pode não ser o mais adequado para todos os erros. Considere o tipo de erro retornado pelo Save e use códigos de status HTTP, só para facilitar a vida

2024-03-08 11:39 UTC, Felipeness approved these changes
O código está bem organizado Excelente. No entanto, faça com mais amor e carinho... não tenha pressa.

2024-03-08 21:27 UTC, luanc202 commented
Calma não aprova não pq a função de Save do Mock ainda tá incompleta

2024-03-08 21:57 UTC, luanc202 commented
Finalizado 👍

2024-03-09 14:30 UTC, k1nha requested changes
Mandou bem e vi que não teve problemas com o Go!

Tem alguns pontos que dá melhorar até porque o fluxo de criação de pet que temos hoje é bem maior, então ficou faltando algumas coisas. Vamos tentar seguir a referência visual da galera do front para fazer esse fluxo no backend. 

[Figma - criação pet](https://www.figma.com/file/ZQ5mPH1j2snuiVpkp68EI5/PetDex?type=design&node-id=1010-1889&mode=design&t=z8BkA5lL0ATY3UCs-4)

Bem provavelmente vamos precisar de um DTO para validar os dados que estamos recebendo e enviar para o usecase, tambem seria válido criar uma factory pra entidade de pet (acho que temos referência disso na *main* ou no pr do lefel)

Qualquer dúvida, só chamar no disc ou vamos discutir essas ideias por aqui mesmo

2024-03-09 14:30 UTC, k1nha commented on api/controllers/pet/create.go
move essa função para o controller de pet, no momento, estamos usando apenas um arquivo por controller

2024-03-09 14:30 UTC, k1nha commented on interfaces/mocks/mocks.go
boaa ideia!! só mudaria o nome do arquivo pra representar que é referente ao `pet repository`

2024-03-09 14:30 UTC, k1nha commented on infra/db/pet_repository.go
> +	err := pr.dbconnection.QueryRow("INSERT INTO pets (name, breedId, userId) VALUES (?, ?, ?) RETURNING id", petToSave.Name, petToSave.BreedID, petToSave.UserID).Scan(&petToSave.ID)
Está faltando algumas informações aqui como tamanho, peso, data de adoção...

Será que precisamos retornar somente o id?

2024-03-11 03:08 UTC, luanc202 commented on api/controllers/pet/create.go
Feito ✅

2024-03-11 03:08 UTC, luanc202 commented on interfaces/mocks/mocks.go
Renomeado para `pet_repository`.go  ✅

2024-03-11 03:09 UTC, luanc202 commented on infra/db/pet_repository.go
> +	err := pr.dbconnection.QueryRow("INSERT INTO pets (name, breedId, userId) VALUES (?, ?, ?) RETURNING id", petToSave.Name, petToSave.BreedID, petToSave.UserID).Scan(&petToSave.ID)
Adicionei os atributos faltantes e retornei os que serão usados no front, que são os mesmos do insert

2024-03-11 03:11 UTC, luanc202 commented
Fiquei só com um problema quando envio uma data para a API e ela não consegue fazer parse numa data de formato YYYY/MM/dd como 2016/11/02 e, se eu passar do jeito que ele pediu, como "2016-08-11T15:04:05Z", dá um `invalid memory address or nil pointer dereference` então eu acredito que não estou sabendo como passar a data para ele no momento de salvar.

2024-03-13 12:28 UTC, devlefel requested changes
Deixei alguns comentarios bros, mas nada muito critico

2024-03-13 12:28 UTC, devlefel commented on api/controllers/pet.go
> +		w.Header().Set("Content-Type", "application/json")
Coloque esse cara ja no inicio do controller para nao ter que setar ele toda vez

2024-03-13 12:28 UTC, devlefel commented on api/main.go
> +		FindPetController:   findPetController,
Cara da um rebase, eu acho que nao temos mais findPetController

2024-03-13 12:28 UTC, devlefel commented on api/main.go
> +		FindPetController:   findPetController,
Se tiver ok

2024-03-13 12:28 UTC, devlefel commented on interfaces/mocks/pet_repository.go
Ta na pasta correta? o ideal eh nao deixarmos em pastas separadas

2024-03-13 12:28 UTC, devlefel commented on api/controllers/pet.go
Faltou um Validade() do dto nao?

2024-03-13 12:28 UTC, devlefel commented on usecase/pet_test.go
> +	mockRepo := new(MockPetRepository)
Para que vc criou o mock em interfaces/mock se ta criando um novo aqui na linha 17?

2024-03-13 16:32 UTC, k1nha commented on api/controllers/pet.go
> +		w.Header().Set("Content-Type", "application/json")
não precisaria mais usar o header set, vamos setar isso no pr #88

2024-03-19 21:51 UTC, luanc202 commented on api/main.go
> +		FindPetController:   findPetController,
Ainda tá lá na main, não mexi nele

2024-03-20 01:24 UTC, luanc202 commented on usecase/pet_test.go
> +	mockRepo := new(MockPetRepository)
Não tinha definido ainda qual seria a forma mais adequada, vou apagar o que ficou na outra pasta daí podemos decidir depois onde colocar os mocks.

2024-03-20 01:38 UTC, luanc202 commented on api/controllers/pet.go
Implementei

2024-03-20 01:38 UTC, luanc202 commented on interfaces/mocks/pet_repository.go
Removido

2024-03-27 00:27 UTC, k1nha requested changes

2024-03-27 00:27 UTC, k1nha commented on api/controllers/pet.go
> +	}
Cara, eu acho que a gente consegue pensar melhor nesse fluxo aqui

- Estamos usando duas vezes o petToSave.validate() duas vezes, a gente pode reatribuir o resultado dessa função ao err 

fiz o código rápido mas a ideia é mais ou menos essa:

```go
        err := json.NewDecoder(r.Body).Decode(&petToSave)
	defer r.Body.Close()
	if err != nil {
		w.WriteHeader(http.StatusBadRequest)
		json.NewEncoder(w).Encode(errors.ErrInvalidBody{
			Description: "The body is invalid",
		})
		return
	}

	err = petToSave.Validate()
	if err != nil {
		w.WriteHeader(http.StatusBadRequest)
		json.NewEncoder(w).Encode(err)
		return
	}
```

2024-03-27 00:27 UTC, k1nha commented on entity/dto/pet_insert_dto.go
> +		return errors.New("name cannot exceed 80 characters")
bom verificar se o a string é vazia também

```suggestion
	if p.Name == "" || len(p.Name) > 80 {
```

2024-04-01 18:08 UTC, luan-alves-develcode commented on entity/dto/pet_insert_dto.go
> +		return errors.New("name cannot exceed 80 characters")
Adicionei a verificação logo na linha debaixo, coloquei em outro if para manter as validações isoladas

2024-04-01 18:09 UTC, luan-alves-develcode commented on api/controllers/pet.go
> +		w.Header().Set("Content-Type", "application/json")
Removi todos

2024-04-11 21:38 UTC, devlefel approved these changes

2024-04-11 21:38 UTC, merged