feat: create logger
devhatt/pet-dex-backend pull request #93
Opened 2024-03-09 14:47 UTC by k1nha

Closes #92 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Essa feature cria um logger para aplicação
</details>

<details open> 
  <summary>
    <b>Bugfix</b>
  </summary>

- **Description**
N/A

- **Cause**
Não estamos fazendo o tracking de erro em ambiente de DEV

- **Solution**
N/A
</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
N/A
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

  - [x] Issue linked
  - [x] Build working correctly
  - [ ] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
N/A
</details>

2024-03-12 12:29 UTC, devlefel requested changes

2024-03-12 12:42 UTC, k1nha commented on infra/config/config.go
> +func GetLogger(p string) *Logger {
não vejo porque fazer, logger é muito pequeno para criar uma abstração e não precisariamos re-escrever muita coisa

2024-03-12 14:52 UTC, kvnbg commented
Acredito que seria interessante adicionar um exemplo de como usar esse Logger pro pessoal ter como base

2024-03-12 15:01 UTC, kvnbg reviewed
Acredito que seria interessante adicionar um exemplo de como usar esse Logger pro pessoal ter como base

2024-03-12 16:41 UTC, k1nha commented
> Acredito que seria interessante adicionar um exemplo de como usar esse Logger pro pessoal ter como base

boaa, verdade

2024-03-18 13:38 UTC, devlefel approved these changes
Saudades de um testes de lib em @k1nha ?
Nao vamos ter uma interface para satisfazer essa implementacao? ou vamos deixar no pelo mesmo?

2024-03-18 13:38 UTC, devlefel commented on infra/config/config.go
> +func InitConfigs() error {
Eu nao entendi essa mudanca

2024-03-18 14:04 UTC, k1nha commented on infra/config/config.go
> +func InitConfigs() error {
VI que não fazia muito sentido a função de `InitConfigs` retornar um ponteiro de db. Faz mais sentido só retornar o erro ou não retornar nada e colocar um panic dentro

2024-03-18 15:26 UTC, kvnbg approved these changes

2024-03-18 15:26 UTC, merged